# Built with Jekyll 3.2.0

# Setup
title:               Shaurya Chopra
tagline:             'Blog & Portfolio'
description:         'Blog for posts about technical stuff, projects and hobbies'
url:                 'https://shchopra.github.io'
#baseurl:             ''

# About/contact
author:
  name:              Shaurya Chopra
  url:               https://schopra.me
  email:             shaurya.d.chopra@gmail.com

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  mathjax:        true
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."

future: true
